### ISSUE TITLE
Packages are capped at ^7.0.0

### ISSUE THREAD

**Issue by kevinSuttle** [babel/babel-upgrade#106]
Shouldn't running `npx babel-upgrade` print the most recent versions of packages instead of stopping at `^7.0.0`? 

e.g. https://github.com/babel/babel/tree/master/packages#other - only `@babel/register` has a version below `7.2.0`.

**Comment by JacobMGEvans** [comment]
I think this tool was just a stop-gap for the upgrade from 6 to 7 I don't think they were planning for long-term support. 

If I am wrong that would actually be awesome.

**Comment by smpeters** [comment]
It'd be great then to state that clearly at the top of the documentation.

**Comment by JLHwung** [comment]
Both npm and yarn will resolve `^7.0.0` to latest 7.x version . e.g. `7.12.0`. To clarify, `babel-upgrade` does not pin babel to `7.0.0`, it is very unlikely you will get `7.0.0` as of now unless you are time travelling to 2017.
