### ISSUE TITLE
Various Node Versions Support

### ISSUE THREAD

**Issue by scurker** [babel/babel-upgrade#13]
This is probably in the early stages, so I apologize if this issue is premature. From the documentation, it looks like the intent is to support node 4 <=, but currently isn't transpiled down to support Node 4.

##### /bin/babel-upgrade
```
const { isAcceptedNodeVersion, writePackageJSON, writeBabelRC } = require("../src");
      ^
SyntaxError: Unexpected token {
```

##### /src/index.js:59
```
async function writePackageJSON() {
      ^^^^^^^^
SyntaxError: Unexpected token function
```

##### /src/packageData.js:243
```
);
^
SyntaxError: Unexpected token )
```

Otherwise, everything has worked great in node 8 & 9 .

**Comment by hzoo** [comment]
Yeah it's in the readme, didn't get to it yet. https://github.com/babel/babel-upgrade/pull/11#issuecomment-367014699

Or if someone wants to make a PR (use babel + target node 4 in the config with preset-env)

**Comment by abouthiroppy** [comment]
I created PR:)
