### ISSUE TITLE
Incorrect update babel-loader for webpack 1

### ISSUE THREAD

**Issue by andrew-polyansky** [babel/babel-upgrade#17]
Webpack: 1.13.2
Node: 8.9.1
npm: 5.6.0

`package.json`
```diff
{
  "devDependencies": {
+   "@babel/core": "7.0.0-beta.39",
+   "@babel/polyfill": "7.0.0-beta.39",
+   "@babel/preset-env": "7.0.0-beta.39",
+   "@babel/preset-react": "7.0.0-beta.39",
+   "@babel/preset-stage-2": "7.0.0-beta.39",
+   "babel-loader": "v8.0.0-beta.0",
-    "babel-core": "6.26.0",
-    "babel-loader": "6.2.5",
-    "babel-polyfill": "6.26.0",
-    "babel-preset-env": "1.6.1",
-    "babel-preset-react": "6.24.1",
-    "babel-preset-stage-2": "6.24.1",
  },
}
```

`.babelrc`
```diff
 {
   "presets": [
-    ["env", {
-      "targets": {
-        "browsers": ["last 2 versions"]
+    [
+      "@babel/preset-env",
+      {
+        "targets": {
+          "browsers": [
+            "last 2 versions"
+          ]
+        }
       }
-    }],
-    "react",
-    "stage-2"
+    ],
+    "@babel/preset-react",
+    "@babel/preset-stage-2"
   ]
 }
```

Error in console: 
```
ERROR in multi app
Module not found: Error: Cannot resolve module 'babel-polyfill' in /home/andrew/w/projects/m-daiquiri-ui
 @ multi app

ERROR in ./core/src/index.jsx
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/home/andrew/w/projects/m-daiquiri-ui/node_modules/babel-loader/lib/utils/exists.js:5:25)
    at find (/home/andrew/w/projects/m-daiquiri-ui/node_modules/babel-loader/lib/resolve-rc.js:12:9)
    at Object.module.exports (/home/andrew/w/projects/m-daiquiri-ui/node_modules/babel-loader/lib/index.js:121:132)
 @ multi app

```

**Comment by existentialism** [comment]
Based on the error message, it looks like you need to change your babel-polyfill import to `@babel/polyfill`.

**Comment by hzoo** [comment]
It doesn't handle modifying js files yet

**Comment by andrew-polyansky** [comment]
@existentialism Yes, that helped for resolve first error.

I have changed: 
```diff
     entry: {
-        app: ['babel-polyfill', PATHS],
+        app: ['@babel/polyfill', PATHS],
     },
```

But I still have by babel-loader:
```
ERROR in ./core/src/index.jsx
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/home/andrew/w/projects/m-daiquiri-ui/node_modules/babel-loader/lib/utils/exists.js:5:25)
    at find (/home/andrew/w/projects/m-daiquiri-ui/node_modules/babel-loader/lib/resolve-rc.js:12:9)
    at Object.module.exports (/home/andrew/w/projects/m-daiquiri-ui/node_modules/babel-loader/lib/index.js:121:132)
 @ multi app

```

**Comment by hzoo** [comment]
https://github.com/babel/babel-loader/issues/505? Not sure because that was on the old version

**Comment by hzoo** [comment]
Ah that's in the title, yeah babel-loader 8 doesn't support webpack 1

**Comment by hzoo** [comment]
Not sure we want to do this at least atm, babel-loader dropped support for webpack 1 a while ago if that makes sense

**Comment by hzoo** [comment]
So maybe the thing we should do is error if you are using webpack 1? And say to upgrade?

**Comment by andrew-polyansky** [comment]
@hzoo there are 2 options:
1) return error and say to upgrade
2) Update babel-loader to the most compatible version `6.x`;
Make warning about it and in case of problems try to upgrade webpack

What do you thin about it?

**Comment by hzoo** [comment]
I was actually goign to say I don't think we can do 2 because `babel-loader` v6 uses `babel-core` not `@babel/core` but maybe it would work with the babel bridge?

If that actually works then 2 would be

- check webpack is v1,
- update babel-loader to v6
- update babel-core to `7.0.0-bridge.0`
- update everything else to scoped as usual

**Comment by adityavohra7** [comment]
@hzoo, mind if I take a stab at this?

**Comment by hzoo** [comment]
For sure. should be straightforward, just need to verify that the solution I say there is correct ^ and actually works.

https://github.com/babel/babel-upgrade/blob/1199f30763c061c49886c707437d1df09beed4d0/src/upgradeDeps.js#L5
https://github.com/babel/babel-upgrade/blob/1199f30763c061c49886c707437d1df09beed4d0/src/index.js#L76-L78
