### ISSUE TITLE
@babel/preset-flow was added twice in package.json

### ISSUE THREAD

**Issue by julienw** [babel/babel-upgrade#74]
I ran the script using `npx`.

Previously `babel-preset-flow` was in `devDependencies` only. After the script ran, `@babel/preset-flow` was added both in `dependencies` and `devDependencies`.

**Comment by nicolo-ribaudo** [comment]
We should add some logic to decide which field should be upgraded at https://github.com/babel/babel-upgrade/blob/683462ca97d00df58bce03f329a0bf91c7b6d76c/src/index.js#L59-L73

**Comment by julienw** [comment]
Looks like the issue is there:
https://github.com/babel/babel-upgrade/blob/683462ca97d00df58bce03f329a0bf91c7b6d76c/src/upgradeDeps.js#L58-L62

If `hasFLow` is true, the dependency will be added in both dictionaries.

**Comment by aulisius** [comment]
We could add a new key to the `options` object to detect if we're modifying `devDependencies` or not.

**Comment by julienw** [comment]
I don't think if that's enough, in the current epoch of webpack, a lot of devs indifferently put the dependencies in either dictionary.

Maybe the check for "hasFlow" shouldn't be in `upgradeDeps` but rather in `index` after the 2 calls, with something like this:
```javascript
if (options.hasFlow &&
    !pkg.dependencies['@babel/preset-flow'] &&
    !pkg.devDependencies['@babel/preset-flow']) {
  pkg.devDependencies['@babel/preset-flow'] = getLatestVersion();
}
